### ISSUE TITLE
Install does not proceed beyond "Downloading Boxcar"

### ISSUE THREAD

**Issue by jinjorge** [nicinabox/boxcar#11]
ran the install cmd and get stuck here

```
# bash <(curl -s http://boxcar.nicinabox.com/install)
Hi! You're about to install Boxcar for unRAID. We'll get you setup with a new web interface and command line tool.
Cool? [y/N] y
Fetching dependencies...
Downloading Boxcar

```

**Comment by nicinabox** [comment]
Ugh, I left in the test host :(. Thanks!

**Comment by jinjorge** [comment]
did you end up building a new release with the correct host? 

wasn't sure as you closed this issue though the issue persists.

Thanks!!

**Comment by nicinabox** [comment]
Ah man, I'm sorry. Not only was the host messed up twice, but when you wget from github you have to specify an output file. It was all kinds of busted. Should be fixed now, if you'd like to try again.

**Comment by jinjorge** [comment]
I did try again.... getting the following

```

bash <(curl -s http://boxcar.nicinabox.com/install)
Hi! You're about to install Boxcar for unRAID. We'll get you setup with a new web interface and command line tool.
Cool? [y/N] y
Fetching dependencies...
Downloading Boxcar
Cannot install /boot/extra/boxcar-0.3.0-noarch-unraid.tgz:  file not found
```

**Comment by nicinabox** [comment]
I think all my tests have been flawed. Just pushed what should be "the fix".

**Comment by jinjorge** [comment]
download is working now. Thanks!!

new issue

```
# bash <(curl -s http://boxcar.nicinabox.com/install)
Hi! You're about to install Boxcar for unRAID. We'll get you setup with a new web interface and command line tool.
Cool? [y/N] y
Fetching dependencies...
Downloading Boxcar
Verifying package boxcar-0.3.0-noarch-unraid.tgz.
Installing package boxcar-0.3.0-noarch-unraid.tgz:
PACKAGE DESCRIPTION:
WARNING:  Package has not been created with 'makepkg'
Executing install script for boxcar-0.3.0-noarch-unraid.tgz.
ln: creating symbolic link `/usr/local/bin/boxcar': File exists
ln: creating symbolic link `/root/.gemrc': File exists
Package boxcar-0.3.0-noarch-unraid.tgz installed.

/usr/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:298:in `to_specs': Could not find 'bundler' (>= 0) among 0 total gem(s) (Gem::LoadError)
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:309:in `to_spec'
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:47:in `gem'
    from /usr/bin/bundle:22:in `<main>'
root@storage2:~# which ruby
/usr/bin/ruby
root@storage2:~# ruby version
ruby: No such file or directory -- version (LoadError)
root@storage2:~# ruby -- version
ruby: No such file or directory -- version (LoadError)
root@storage2:~# ruby --version
ruby 1.9.3p448 (2013-06-27 revision 41675) [i486-linux]
```

**Comment by nicinabox** [comment]
Can you give the output of `gem env`?

**Comment by jinjorge** [comment]
here you go

```
# gem env
/usr/lib/ruby/site_ruby/1.9.1/rubygems/commands/environment_command.rb:148:
warning: Insecure world writable dir /boot in PATH, mode 040777
RubyGems Environment:
  - RUBYGEMS VERSION: 2.1.10
  - RUBY VERSION: 1.9.3 (2013-06-27 patchlevel 448) [i486-linux]
  - INSTALLATION DIRECTORY: /boot/custom/gems/ruby/1.9.1
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /boot/custom/gems/ruby/1.9.1/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-linux
  - GEM PATHS:
     - /boot/custom/gems/ruby/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :ssl_verify_mode => 0
     - "gem" => "--no-ri --no-rdoc"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /boot/custom/gems/ruby/1.9.1/bin
     - .
     - /usr/local/sbin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/kerberos/bin
     - /usr/kerberos/sbin
```

**Comment by nicinabox** [comment]
That looks good. try reopening your terminal session and trying again? I haven't seen this failure in my testing.

**Comment by jinjorge** [comment]
decided to give this another try after updaing to unRAID 5.0.2. looks to be making progress, though not quite there

```
Fetching gem metadata from https://rubygems.org/..
/boot/custom/gems/ruby/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:284: warning: Insecure world writable dir /boot/custom/gems/ruby/1.9.1/bin in PATH, mode 040777
Installing backports (3.3.3)
Installing chunky_png (1.2.8)
Installing fssm (0.2.10)
Installing sass (3.2.10)
Installing compass (0.12.2)
Installing safe_yaml (0.9.5)
Installing crack (0.4.1)
Installing daemons (1.1.9)
Installing diff-lcs (1.2.4)
Installing erubis (2.7.0)
Installing escape_utils (0.3.2)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h


Gem files will remain installed in /boot/custom/gems/ruby/1.9.1/gems/escape_utils-0.3.2 for inspection.
Results logged to /boot/custom/gems/ruby/1.9.1/gems/escape_utils-0.3.2/ext/escape_utils/gem_make.out

An error occurred while installing escape_utils (0.3.2), and Bundler cannot continue.
Make sure that `gem install escape_utils -v '0.3.2'` succeeds before bundling.
root@storage2:~#

root@storage2:~# more /boot/custom/gems/ruby/1.9.1/gems/escape_utils-0.3.2/ext/escape_utils/gem_make.out
/usr/bin/ruby extconf.rb
creating Makefile

make
compiling buffer.c
buffer.c:8:19: fatal error: ctype.h: No such file or directory
compilation terminated.
make: *** [buffer.o] Error 1
root@storage2:~#

```

any ideas?

Thanks!

**Comment by nicinabox** [comment]
No idea why this happens, but sometimes errors occur on missing files that should be been copied by previously installed packages. In this case, ruby.h comes from the ruby package and it would have already been installed through the boxcar installer.

I made a [wiki page to collect up the common errors](https://github.com/nicinabox/boxcar/wiki/Common-errors-on-install) and what to reinstall.

**Comment by jinjorge** [comment]
I did reinstall ruby\* and run the boxcar install again and got the same
error. :(

**Comment by nicinabox** [comment]
Hmm, I'm not able to duplicate this. Using 5.0.2.
