### ISSUE TITLE
An error occurred while installing atomic (1.1.10), and Bundler cannot continue

### ISSUE THREAD

**Issue by jinjorge** [nicinabox/boxcar#9]
not sure what happened during the install process, now stuck in a loop where any boxcar cmds run on the command line end up with the following output

```
root@storage2:/boot/config# boxcar update
Latest version currently installed. Aborting.
Successfully installed bundler-1.3.5
1 gem installed
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
/usr/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:284: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
Using i18n (0.6.4)
Using minitest (4.7.5)
Using multi_json (1.7.7)
Installing atomic (1.1.10)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h


Gem files will remain installed in /usr/lib/ruby/gems/1.9.1/gems/atomic-1.1.10 for inspection.
Results logged to /usr/lib/ruby/gems/1.9.1/gems/atomic-1.1.10/ext/gem_make.out

An error occurred while installing atomic (1.1.10), and Bundler cannot continue.
Make sure that `gem install atomic -v '1.1.10'` succeeds before bundling.
ln: creating symbolic link `/usr/local/bin/boxcar': File exists
/usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- sinatra (LoadError)
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /usr/apps/boxcar/config/environment.rb:1:in `<top (required)>'
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /usr/apps/boxcar/lib/boxcar.rb:6:in `<top (required)>'
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /usr/local/bin/boxcar:9:in `<main>'
root@storage2:/boot/config#
```

How do I start off clean as running 'boxcar uninstall' yields the same output above?

Thanks!!

J

**Comment by nicinabox** [comment]
First check the mkmf.log created by the failure (find with: `find / -name mkmf.log`). That will have some clues as to what dependency is missing.

**Comment by jinjorge** [comment]
ok. will take a look this evening and report back.

Thanks for the help!

**Comment by jinjorge** [comment]
can't find the mkmf.log file :(

**Comment by nicinabox** [comment]
Silly me, I missed this line in the log up there: `mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h`.

Presumably you need to run the ruby install again. `cd /boot/extra/ && installpkg ruby*`

**Comment by jinjorge** [comment]
I've give that a shot tonight.

Thanks for your help.

**Comment by nicinabox** [comment]
Yes. This is going to be changing soon though.

**Comment by jinjorge** [comment]
ok, got a little further now and have a mkmf.log file. Still having issues installing atomic gem

```
Installing atomic (1.1.10)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby
    --with-atomic_reference-dir
    --without-atomic_reference-dir
    --with-atomic_reference-include
    --without-atomic_reference-include=${atomic_reference-dir}/include
    --with-atomic_reference-lib
    --without-atomic_reference-lib=${atomic_reference-dir}/
/usr/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /usr/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
    from /usr/lib/ruby/1.9.1/mkmf.rb:712:in `try_run'
    from extconf.rb:22:in `<main>'


Gem files will remain installed in /usr/lib/ruby/gems/1.9.1/gems/atomic-1.1.10 for inspection.
Results logged to /usr/lib/ruby/gems/1.9.1/gems/atomic-1.1.10/ext/gem_make.out

An error occurred while installing atomic (1.1.10), and Bundler cannot continue.
Make sure that `gem install atomic -v '1.1.10'` succeeds before bundling.
Packing...
./
boot/
boot/config/
boot/config/boxcar
```

and the mkmf.log file looks as such

```
root@storage2:/usr/lib/ruby/gems/1.9.1/gems/atomic-1.1.10/ext# more mkmf.log
"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lpthread -lrt -ldl -lcrypt -lm
-lc"
/usr/lib/ruby/1.9.1/mkmf.rb:317: warning: Insecure world writable dir /usr/lib/ruby/gems/1.9.1/gems/atomic-1.1.10/ext/. in PATH, mode 040777
In file included from /usr/include/bits/posix1_lim.h:157:0,
                 from /usr/include/limits.h:145,
                 from /usr/lib/gcc/i486-slackware-linux/4.5.2/include-fixed/limits.h:169,
                 from /usr/lib/gcc/i486-slackware-linux/4.5.2/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/i486-slackware-linux/4.5.2/include-fixed/limits.h:34,
                 from /usr/include/ruby-1.9.1/ruby/ruby.h:178,
                 from /usr/include/ruby-1.9.1/ruby.h:32,
                 from conftest.c:1:
/usr/include/bits/local_lim.h:39:26: fatal error: linux/limits.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

root@storage2:/usr/lib/ruby/gems/1.9.1/gems/atomic-1.1.10/ext#
```

also getting the following error at the very end of the install process

```
usr/apps/boxcar/Gemfile
usr/apps/boxcar/log/
ln: creating symbolic link `/usr/local/bin/boxcar': File exists
rake aborted!
cannot load such file -- sinatra/assetpack/rake

(See full trace by running task with --trace)
Updating /boot/config/go to start Boxcar on boot...
/usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- grit (LoadError)
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /usr/apps/boxcar/lib/boxcar/command/addons.rb:3:in `<top (required)>'
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /usr/apps/boxcar/lib/boxcar/command.rb:10:in `block in load'
    from /usr/apps/boxcar/lib/boxcar/command.rb:9:in `each'
    from /usr/apps/boxcar/lib/boxcar/command.rb:9:in `load'
    from /usr/apps/boxcar/lib/boxcar/cli.rb:7:in `start'
    from /usr/apps/boxcar/lib/boxcar.rb:10:in `<top (required)>'
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /usr/local/bin/boxcar:9:in `<main>'
===================================================================
 Boxcar installed! Visit http://storage2:3000 for awesomeness
 Report issues at:
  https://github.com/nicinabox/boxcar/issues
===================================================================
root@storage2:/boot/extra#

```

How are does the installer determine a successful Boxcar install when there were issues installing the underlying dependencies?

Thanks!

**Comment by nicinabox** [comment]
You're missing linux/limits.h. It's part of the kernel-headers package. Same procedure as before, just install kernel-headers instead of ruby.

Unfortunately the installer is not yet sophisticated enough to halt when there's a failure within a sub-process. It show's the "success" message regardless.

**Comment by jinjorge** [comment]
ahh, makes sense on the installer.

I am inching ever so close though another bump :(

This time it's running into problems installing the eventmachine gem

```

Installing escape_utils (0.3.2)
Installing eventmachine (1.0.3)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
/usr/lib/ruby/1.9.1/mkmf.rb:1356: warning: Insecure world writable dir /usr/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/ext/. in PATH, mode 040777
checking for main() in -lssl... yes
checking for main() in -lcrypto... yes
checking for openssl/ssl.h... no
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... yes
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
creating Makefile

make
compiling ssl.cpp
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.20110118.so)
compiling rubymain.cpp
In file included from rubymain.cpp:20:0:
project.h:29:20: fatal error: iostream: No such file or directory
compilation terminated.
make: *** [rubymain.o] Error 1


Gem files will remain installed in /usr/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3 for inspection.
Results logged to /usr/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/ext/gem_make.out

An error occurred while installing eventmachine (1.0.3), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.
Packing...
./
boot/
boot/config/
```

and the output of the mkmf.log file...

```
root@storage2:/usr/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/ext# more mkmf.log
package configuration for openssl is not found
have_library: checking for main() in -lssl... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lpthread -lrt -ldl -lcrypt -lm
-lc"
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/ld: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lpthread -lrt -ldl -lcrypt
-lm   -lc"
conftest.c: In function ‘t’:
conftest.c:4:53: error: ‘main’ undeclared (first use in this function)
conftest.c:4:53: note: each undeclared identifier is reported only once for each function it appears in
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: int t() { void ((*volatile p)()); p = (void ((*)()))main; return 0; }
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
/* end */

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lpthread -lrt -ldl -lcrypt
-lm   -lc"
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/ld: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: int t() { main(); return 0; }
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
/* end */

--------------------

have_library: checking for main() in -lcrypto... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpthread -lr
t -ldl -lcrypt -lm   -lc"
conftest.c: In function ‘t’:
conftest.c:4:53: error: ‘main’ undeclared (first use in this function)
conftest.c:4:53: note: each undeclared identifier is reported only once for each function it appears in
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: int t() { void ((*volatile p)()); p = (void ((*)()))main; return 0; }
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
/* end */

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpthread -lr
t -ldl -lcrypt -lm   -lc"
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/ld: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: int t() { main(); return 0; }
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
/* end */

--------------------

have_header: checking for openssl/ssl.h... -------------------- no

"gcc -E -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -fno-strict
-aliasing -fPIC  conftest.c -o conftest.i"
conftest.c:3:25: fatal error: openssl/ssl.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <openssl/ssl.h>
/* end */

--------------------

have_var: checking for rb_trap_immediate in ruby.h,rubysig.h... -------------------- no

"gcc -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -fno-strict-al
iasing -fPIC   -c conftest.c"
In file included from conftest.c:4:0:
/usr/include/ruby-1.9.1/ruby/backward/rubysig.h:14:2: warning: #warning rubysig.h is obsolete
conftest.c: In function ‘t’:
conftest.c:7:51: error: ‘rb_trap_immediate’ undeclared (first use in this function)
conftest.c:7:51: note: each undeclared identifier is reported only once for each function it appears in
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: #include <ruby.h>
 4: #include <rubysig.h>
 5:
 6: /*top*/
 7: int t() { const volatile void *volatile p; p = &(&rb_trap_immediate)[0]; return 0; }
 8: int main(int argc, char **argv)
 9: {
10:   if (argc > 1000000) {
11:     printf("%p", &t);
12:   }
13:
14:   return 0;
15: }
/* end */

--------------------

have_func: checking for rb_thread_blocking_region()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -lcrypto -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpt
hread -lrt -ldl -lcrypt -lm   -lc"
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/ld: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: int t() { void ((*volatile p)()); p = (void ((*)()))rb_thread_blocking_region; return 0; }
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
/* end */

--------------------

have_func: checking for inotify_init() in sys/inotify.h... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -lcrypto -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpt
hread -lrt -ldl -lcrypt -lm   -lc"
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/ld: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: #include <sys/inotify.h>
 4:
 5: /*top*/
 6: int t() { void ((*volatile p)()); p = (void ((*)()))inotify_init; return 0; }
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12:
13:   return 0;
14: }
/* end */

--------------------

have_func: checking for writev() in sys/uio.h... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -lcrypto -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpt
hread -lrt -ldl -lcrypt -lm   -lc"
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/ld: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: #include <sys/uio.h>
 4:
 5: /*top*/
 6: int t() { void ((*volatile p)()); p = (void ((*)()))writev; return 0; }
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12:
13:   return 0;
14: }
/* end */

--------------------

have_func: checking for rb_wait_for_single_fd()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -lcrypto -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpt
hread -lrt -ldl -lcrypt -lm   -lc"
conftest.c: In function ‘t’:
conftest.c:4:53: error: ‘rb_wait_for_single_fd’ undeclared (first use in this function)
conftest.c:4:53: note: each undeclared identifier is reported only once for each function it appears in
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: int t() { void ((*volatile p)()); p = (void ((*)()))rb_wait_for_single_fd; return 0; }
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
/* end */

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -lcrypto -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpt
hread -lrt -ldl -lcrypt -lm   -lc"
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/ld: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: int t() { rb_wait_for_single_fd(); return 0; }
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
/* end */

--------------------

have_func: checking for rb_enable_interrupt()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -lcrypto -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpt
hread -lrt -ldl -lcrypt -lm   -lc"
conftest.c: In function ‘t’:
conftest.c:4:53: error: ‘rb_enable_interrupt’ undeclared (first use in this function)
conftest.c:4:53: note: each undeclared identifier is reported only once for each function it appears in
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: int t() { void ((*volatile p)()); p = (void ((*)()))rb_enable_interrupt; return 0; }
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
/* end */

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -lcrypto -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpt
hread -lrt -ldl -lcrypt -lm   -lc"
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/ld: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: int t() { rb_enable_interrupt(); return 0; }
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
/* end */

--------------------

have_func: checking for rb_time_new()... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -lcrypto -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpt
hread -lrt -ldl -lcrypt -lm   -lc"
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/ld: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: int t() { void ((*volatile p)()); p = (void ((*)()))rb_time_new; return 0; }
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
/* end */

--------------------

have_header: checking for sys/event.h... -------------------- no

"gcc -E -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -fno-strict
-aliasing -fPIC  conftest.c -o conftest.i"
conftest.c:3:23: fatal error: sys/event.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <sys/event.h>
/* end */

--------------------

have_func: checking for epoll_create() in sys/epoll.h... -------------------- yes

"gcc -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -lcrypto -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby  -lssl -lcrypto -lpt
hread -lrt -ldl -lcrypt -lm   -lc"
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/as: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
/usr/lib/gcc/i486-slackware-linux/4.5.2/../../../../i486-slackware-linux/bin/ld: /usr/lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.21.51.0.6.2011
0118.so)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: #include <sys/epoll.h>
 4:
 5: /*top*/
 6: int t() { void ((*volatile p)()); p = (void ((*)()))epoll_create; return 0; }
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12:
13:   return 0;
14: }
/* end */

--------------------

"g++ -o conftest -I/usr/include/ruby-1.9.1/i486-linux -I/usr/include/ruby-1.9.1/ruby/backward -I/usr/include/ruby-1.9.1 -I.  -D_FILE_OFFSET_BITS=64  -march=i486 -mtune=i686 -O3 -f
no-strict-aliasing -fPIC conftest.c  -L. -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic     -lssl -lcrypto -Wl,-R -Wl,/usr/lib -L/usr/lib -lruby -lstdc++ -lpthread -
lrt -ldl -lcrypt -lm   -lc"
conftest.c:3:21: fatal error: utility: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3:   #include <utility>
4:   using namespace std;
5:   int main(){ pair<int,int> tuple = make_pair(1,2); }
/* end */

root@storage2:/usr/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/ext#
```

**Comment by nicinabox** [comment]
I've decided to remove the ActiveRecord dependency. It causes lots of unreliability and it's barely being used. So, in favor of stability, AR will be removed in the next version.

**Comment by jinjorge** [comment]
ok, let me know when the next version is available and I'll give it a whirl.

Thanks!

**Comment by nicinabox** [comment]
0.3.0 is released :)
